import type { Event } from '../types';

export const dummyEvents: Event[] = [
  {
    id: '1',
    title: '이벤트 1',
    date: '2025-06-01',
    startTime: '14:30',
    endTime: '16:00',
    description: '설명',
    location: '장소',
    category: '카테고리',
    repeat: { type: 'none', interval: 1 },
    notificationTime: 30,
  },
  {
    id: '2',
    title: '이벤트 2',
    date: '2025-05-02',
    startTime: '14:30',
    endTime: '16:00',
    description: '설명',
    location: '장소',
    category: '카테고리',
    repeat: { type: 'none', interval: 1 },
    notificationTime: 30,
  },
  {
    id: '3',
    title: '이벤트 3',
    date: '2025-04-15',
    startTime: '14:30',
    endTime: '16:00',
    description: '설명',
    location: '장소',
    category: '카테고리',
    repeat: { type: 'none', interval: 1 },
    notificationTime: 30,
  },
  {
    id: '4',
    title: '이벤트 4',
    date: '2025-07-12',
    startTime: '14:30',
    endTime: '16:00',
    description: '설명',
    location: '장소',
    category: '카테고리',
    repeat: { type: 'none', interval: 1 },
    notificationTime: 30,
  },
  {
    id: '5',
    title: '이벤트 5',
    date: '2024-04-01',
    startTime: '14:30',
    endTime: '16:00',
    description: '설명',
    location: '장소',
    category: '카테고리',
    repeat: { type: 'none', interval: 1 },
    notificationTime: 30,
  },
  {
    id: '6',
    title: '이벤트 6',
    date: '2024-04-01',
    startTime: '11:30',
    endTime: '17:00',
    description: '설명',
    location: '장소',
    category: '카테고리',
    repeat: { type: 'none', interval: 1 },
    notificationTime: 30,
  },
  {
    id: '7',
    title: '이벤트 7',
    date: '2024-04-01',
    startTime: '13:30',
    endTime: '18:00',
    description: '설명',
    location: '장소',
    category: '카테고리',
    repeat: { type: 'none', interval: 1 },
    notificationTime: 30,
  },
];
