import { Event } from '../types';

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    title: '이벤트 1',
    date: '2025-05-01',
    startTime: '09:01',
    endTime: '10:00',
    description: '설명 1',
    location: '회의실 A',
    category: '업무',
    repeat: { type: 'none', interval: 0 },
    notificationTime: 1,
  },
  {
    id: '2',
    title: '이벤트 2',
    date: '2025-07-01',
    startTime: '14:00',
    endTime: '15:00',
    description: '설명 2',
    location: '회의실 B',
    category: '업무',
    repeat: { type: 'none', interval: 0 },
    notificationTime: 1,
  },
  {
    id: '3',
    title: '이벤트 3',
    date: '2025-07-15',
    startTime: '09:00',
    endTime: '10:00',
    description: '설명 3',
    location: '회의실 C',
    category: '개인',
    repeat: { type: 'none', interval: 0 },
    notificationTime: 1,
  },
  {
    id: '6',
    title: 'Event 4',
    date: '2025-07-31',
    startTime: '16:00',
    endTime: '17:00',
    description: 'description 4',
    location: 'Room D',
    category: '기타',
    repeat: { type: 'none', interval: 0 },
    notificationTime: 1,
  },
];
